pull_request_rules:
  - name: label renku-bot's PRs
    conditions:
      - author=RenkuBot
    actions:
      label:
        add: ["dependencies"]
  - name: automatically merge renku-bot PRs on CI success
    conditions:
      - author=RenkuBot
      - base=developement
      - status-success=ci
    actions:
      merge:
        method: merge
