services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
    environment:
      SBT_OPTS: "-Xmx2G"
      RS_SOLR_HOST: "solr"
      RS_SOLR_URL: "http://solr:8983"
      RS_SOLR_CORE: "rsdev-test"
      RS_REDIS_HOST: "redis"
      RS_REDIS_PORT: "6379"
      RS_CONTAINER: "redis"
      RS_LOG_LEVEL: "3"
      RS_SEARCH_HTTP_SERVER_PORT: "8080"
      RS_SEARCH_HTTP_SHUTDOWN_TIMEOUT: "0ms"
      RS_PROVISION_HTTP_SERVER_PORT: "8082"
      RS_PROVISION_HTTP_SHUTDOWN_TIMEOUT: "0ms"
      RS_METRICS_UPDATE_INTERVAL: "0s"
      RS_SOLR_CREATE_CORE_CMD: "bash /workspace/create_solr_core.sh %s"
      RS_SOLR_DELETE_CORE_CMD: "bash /workspace/delete_solr_core.sh %s"
      RS_JWT_ALLOWED_ISSUER_URL_PATTERNS: "renku.ch,*.renku.ch,*.*.renku.ch"
      NO_SOLR: "true"
      NO_REDIS: "true"

  solr:
    image:  bitnami/solr:9

  redis:
    image: bitnami/redis:7.4
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
