#!/usr/bin/env bash
set -oe pipefail

redis_host=${RS_REDIS_HOST:-rsdev}
redis_port=${RS_REDIS_PORT:-6379}
queue_name=$RS_REDIS_QUEUE_userAdded

id=$(head -c 16 < /dev/urandom | base64)
vis="PUBLIC"
while true; do
      case "$1" in
          --id)
              shift; id="$1"; shift
              ;;
          --fname)
              shift; fname="$1"; shift
              ;;
          --lname)
              shift; lname="$1"; shift
              ;;
          *) break
             ;;
      esac
done
if [ -z "$lname" ] || [ -z "$fname" ]; then
    echo "Provide a user name, please."
    exit 1
fi


header='{
  "source":"dev",
  "type":"user.add",
  "dataContentType":"application/avro+json",
  "schemaVersion":"V1",
  "time":0,
  "requestId":"r1"
}'
payload_tpl='{
  "id":$id,
  "firstName":{"string":$fname},
  "lastName":{"string":$lname},
  "email":{"null": null}
}'
payload=$(jq --null-input --arg id "$id" --arg fname "$fname" --arg lname "$lname" "$payload_tpl")

echo redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
