#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Provide a project id and name, please."
    exit 1
fi

redis_host=${RS_REDIS_HOST:-rsdev}
redis_port=${RS_REDIS_PORT:-6379}

header='{"source":"dev","type":"project.created","dataContentType":"application/avro+json","schemaVersion":"1","time":0,"requestId":"r1"}'
payload=$(jq --null-input --arg id "$1" --arg name "$2" --arg slug "$1/$2" '{"id":$id,"name":$name,"slug":$slug, "repositories":[],"visibility":"PUBLIC","description":{"string":"my project description"},"createdBy":"dev","creationDate":0,"members":[]}')

redis-cli -h $redis_host -p $redis_port XADD events '*' headers "$header" payload "$payload"
