#!/usr/bin/env bash
set -oe pipefail

redis_host=${RS_REDIS_HOST:-rsdev}
redis_port=${RS_REDIS_PORT:-6379}
queue_name=$RS_REDIS_QUEUE_projectAuthRemoved

role="MEMBER"
while true; do
      case "$1" in
          --project)
              shift; project="$1"; shift
              ;;
          --user)
              shift; user="$1"; shift
              ;;
          *) break
             ;;
      esac
done
if [ -z "$project" ] || [ -z "$user" ]; then
    echo "Provide a user and project id, please."
    exit 1
fi


header='{
  "source":"dev",
  "type":"authorization.removed",
  "dataContentType":"application/avro+json",
  "schemaVersion":"V1",
  "time":0,
  "requestId":"r1"
}'
payload_tpl='{
  "projectId":$project,
  "userId":$user
}'
payload=$(jq --null-input --arg project "$project" --arg user "$user" "$payload_tpl")

echo redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
