#!/usr/bin/env bash
set -oe pipefail

redis_host=${RS_REDIS_HOST:-rsdev}
redis_port=${RS_REDIS_PORT:-6379}
queue_name=$RS_REDIS_QUEUE_projectRemoved

while true; do
      case "$1" in
          --id)
              shift; id="$1"; shift
              ;;
          *) break
             ;;
      esac
done
if [ -z "$id" ]; then
    echo "Provide a project id, please."
    exit 1
fi


header='{
  "source":"dev",
  "type":"project.removed",
  "dataContentType":"application/avro+json",
  "schemaVersion":"V1",
  "time":0,
  "requestId":"r1"
}'
payload_tpl='{
  "id":$id,
}'
payload=$(jq --null-input --arg id "$id" --arg name "$name" --arg slug "$name/$id" --arg vis "$vis" "$payload_tpl")

echo redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
redis-cli -h $redis_host -p $redis_port XADD $queue_name '*' headers "$header" payload "$payload"
