#!/usr/bin/env bash

set -e

port=${1:-28983}
if [ -z "$RENKU_ENV" ]; then
    echo "Please set RENKU_ENV environment variable to the deployment"
    echo "environment you want to run against"
    exit 1
fi

get_pod_name() {
    local pat="$1"
    kubectl -n $RENKU_ENV get pods -o json|jq -r '.items[]|.metadata.name'|grep "$pat"
}

get_solr_pod() {
    local core_name=${SOLR_CORE_NAME:-renku-search}
    pod_name=$(get_pod_name solr-0)
    echo $pod_name
}

get_solr_secret() {
    local pod_name="$1"
    local solr_pass=$(kubectl -n $RENKU_ENV get secrets -o json | jq -r '.items[]|select(.metadata.labels."app.kubernetes.io/component" == "solr")|.data."solr-password"|@base64d')
    echo "*** solr secret ***"
    echo "user: admin"
    echo "password: $solr_pass"
    echo "Url: http://localhost:$port"
}

pod="$(get_solr_pod)"
get_solr_secret "$pod"
kubectl -n $RENKU_ENV port-forward $pod $port:8983
