name: Auto approve

on:
  pull_request_target

concurrency:
  group: auto-approve-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Info output
        run: echo '${{ github.actor }}'
      - name: Auto approve ${{ github.actor }}
        if: github.actor == 'RenkuBot'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.PAT_EIKEK }}
