name: Auto approve

on:
  pull_request_target

concurrency:
  group: auto-approve-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'RenkuBot[bot]'
    steps:
      - name: Auto approve ${{ github.actor }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.PAT_EIKEK }}
