name: Auto approve

on:
  pull_request_target

concurrency:
  group: auto-approve-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'RenkuBot'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
