name: Auto approve

on:
  pull_request_target

concurrency:
  group: auto-approve-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: some output
        run: echo "${{ github.actor }}"

