name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  ci-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 'openjdk@1.17' ]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 100
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      # - name: Coursier cache
      #   uses: coursier/cache-action@v6
      - name: sbt ci ${{ github.ref }}
        run: sbt -mem 2048 ci
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.RENKU_DOCKER_USERNAME }}
      #     password: ${{ secrets.RENKU_DOCKER_PASSWORD }}
      # - name: sbt docker:publishLocal
      #   run: sbt -mem 2048 cli/Docker/publishLocal
  ci:
    runs-on: ubuntu-latest
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
