name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
      - name: sbt ci ${{ github.ref }}
        env:
          README_BASE_REF: origin/${{ github.base_ref }}
        run: nix develop .#ci --command sbt ci
  ci:
    runs-on: ubuntu-latest
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
